### ISSUE TITLE
Server search quantity does not change

### ISSUE THREAD

**Issue by edgar009955** [yourmnbbn/smext-fakequeries#14]
In the game, in the search for servers, the number of fake players does not change, it changes only in the search for servers through the Steam browser and in the favorites.

////
В игре, в поиске серверов, не меняется количество фейк игроков, меняется только в поиске серверов через Steam браузер и в избранном.

**Comment by edgar009955** [comment]
Maybe I'm doing something wrong?

**Comment by yourmnbbn** [comment]
This issue is duplicated. #4 is talking about the same thing. Basically in the ‘Internet’ tab of the server browser, all the information is from the query except real player count. Real player count is counted by steam master server through player authentication. For more info you can see the comments there.

**Comment by edgar009955** [comment]
i replaced 
int maxClients = g_pServer->GetNumClients();
на,
int maxClients = g_pServer->GetNumClients()+g_pServer->GetNumFakeClients();

And with compiled
and there is no change

**Comment by edgar009955** [comment]
[Fake Queries] Look up ValidateChallengeFunc signature failed 
in error.log
only this error

**Comment by yourmnbbn** [comment]
> i replaced int maxClients = g_pServer->GetNumClients(); на, int maxClients = g_pServer->GetNumClients()+g_pServer->GetNumFakeClients();
> 
> And with compiled and there is no change

Yeah, it’s not about the query, player number displayed in the search result or ‘Internet’ browser is got directly from the steam master server. Any efforts on the query level would be in vain. 


> [Fake Queries] Look up ValidateChallengeFunc signature failed
> in error.log
> only this error

Can you provide OS version information? I didn’t see changes on steamclient library after the latest update.

**Comment by edgar009955** [comment]
Linux version 5.15.11-xanmod1 (root@mascote) (gcc-11 (Debian 11.2.0-12) 11.2.0, GNU ld (GNU Binutils for Debian) 2.37) #0~git20211222.96a4b9e SMP Wed Dec 22 18:01:17 UTC 2021
