### ISSUE TITLE
[Fake Queries] Look up ValidateChallengeFunc signature failed

### ISSUE THREAD

**Issue by edgar009955** [yourmnbbn/smext-fakequeries#15]
L 01/02/2022 - 11:38:41: [Fake Queries] Look up ValidateChallengeFunc signature failed

Debian 9

**Comment by yourmnbbn** [comment]
This issue has been reported in #4 in the last few comments. And has been proved solved by who reported it. Maybe there is still some problems with the steamclient binary signature scanning in Debian. I’ll take a look when I have time later.

**Comment by yourmnbbn** [comment]
I've checked the extension(v1.3.2) on Debian 9 and it works fine, there was no signature lookup failure. Some discussion in #4 has mentioned that some servers are nosteam servers of which the steamclient binary was modified. So make sure you're not using nosteam on your server. 

All the signatures from steamclient binary was used to fix a very rare circumstance shown below that you might never encounter, so this lookup failure won't affect any features of the extension. 
> Some 3rd party query tools will firstly request for a challenge number, then use it to request A2S_INFO, A2S_RULES etc at the same time. Tools with this kind of implementation is not supported when using this extension.

**Comment by yourmnbbn** [comment]
Hey, this is a false error report due to the incomplete check. Commit 1d89d94 has fixed this problem.
