### ISSUE TITLE
Does not display fake information in the global search and also in the favorites.

### ISSUE THREAD

**Issue by 1MazyrS1** [yourmnbbn/smext-fakequeries#17]
Does not display fake information in the global search and also in the favorites.

What needs to be changed to fix this?
Sorry, I'm just new to this stuff and still don't fully understand.

My SP file 
![image](https://user-images.githubusercontent.com/99059343/152626507-1458667d-c158-4e51-93bd-8dbb8cdc47b9.png)

**Comment by yourmnbbn** [comment]
Check if both the extension and your plugin are loaded without errors. 

You're not setting the name, map or any other information of the server except fake players. So assuming you're expecting the player count to be changed accordingly, you have commented the function shown below which you shouldn't.
https://github.com/yourmnbbn/smext-fakequeries/blob/eefeb292f7ca402a12b9ab7e841a7156d54a9e97/example_fakeplayers.sp#L29

**Comment by 1MazyrS1** [comment]
BUDDY THIS IS AWESOME IT WORKS!!!!!!
![image](https://user-images.githubusercontent.com/99059343/154825919-8f6fb9fe-746d-4ec8-baaa-66481072ccd6.png)

**Comment by 1MazyrS1** [comment]
THX!!!
