### ISSUE TITLE
error in the plugin operation

### ISSUE THREAD

**Issue by VIMOVZ** [yourmnbbn/smext-fakequeries#19]
Hello. Compiled the plugin, gives an error: Native "FQ_ResetA2sInfo" was not found

Tell me what is my mistake

**Comment by yourmnbbn** [comment]
Check if the extension is successfully loaded, you could either use `sm exts list` command in the console or check the error log.

**Comment by VIMOVZ** [comment]
now a new error
[SM] Unable to load extension "fakequeries.ext": /home/csgo/server/bin/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/csgo/server/csgo/addons/sourcemod/extensions/fakequeries.ext.2.csgo.so)

**Comment by yourmnbbn** [comment]
See [this comment](https://github.com/yourmnbbn/smext-fakequeries/issues/13#issuecomment-1002380614).

**Comment by VIMOVZ** [comment]
Thanks, your instructions helped. How to make fake players appear in the global search?

**Comment by yourmnbbn** [comment]
The player count in the global search result is not from the query, briefly it's counted by the steam master server through steam authentication. For more information see the comments in #4.
