### ISSUE TITLE
Download ext

### ISSUE THREAD

**Issue by gost442** [yourmnbbn/smext-fakequeries#20]
How  i can download this ext to Linux?

**Comment by gost442** [comment]
![image](https://user-images.githubusercontent.com/77125267/161044765-5656f6a8-2434-4837-857a-0a0d580ba7f2.png)

**Comment by gost442** [comment]
where i can get #include <steam_gameserver.h> ?

**Comment by yourmnbbn** [comment]
Download the pre-build binary in the release or see the documentation of ambuild if you want to compile on your own. Make sure you have all the proper sdks(sourcemod, metamod and hl2sdk-csgo).
