### ISSUE TITLE
Doesn't Work With Incoming New Update

### ISSUE THREAD

**Issue by diablobash** [yourmnbbn/smext-fakequeries#22]
The plugin is not working due to the latest CS:GO update. As soon as I install the plugin the server crashes.

**Comment by yourmnbbn** [comment]
Thanks for the feedback, I'll fix this within a few hours.

**Comment by yourmnbbn** [comment]
Could you please confirm the updated gamedata working if you are using linux? For now I don't have a valid linux test environment, thanks.

**Comment by diablobash** [comment]
Yes it worked thanks. How can we update ourselves when this game data is updated.

**Comment by yourmnbbn** [comment]
For the offsets that's often changed you have to locate the corresponding parts of code in the disassembler and relocate the offset. And the signatures are not that often changed. I've commented the necessary strings to help to locate the function. If you're not able to do this yourself, you can inform me every time of the crash or the signature failure, I'll update this within a day.

**Comment by diablobash** [comment]
We set the maximum number of players to 64 and we can insert a maximum of 64 players. Is it possible to increase this figure further or does Valve only allow this much?

**Comment by yourmnbbn** [comment]
This is only limited by the display logic of the browser, you can try to set any value you want, it doesn't have any impact on the actual max slots in the server.
