### ISSUE TITLE
fakequeries.ext

### ISSUE THREAD

**Issue by Majkovsky** [yourmnbbn/smext-fakequeries#23]
[SM] Unable to load extension "fakequeries.ext": /csgo/addons/sourcemod/extensions/fakequeries.ext.so: cannot open shared object file: No such file or directory

how to make an ext? can I get a ready ext? thanks.

**Comment by yourmnbbn** [comment]
Download pre-compiled binary in the release [here](https://github.com/yourmnbbn/smext-fakequeries/releases/tag/fakequeries_v1.3.3).
