### ISSUE TITLE
error startup plugin, help me :(

### ISSUE THREAD

**Issue by ua-player-ua** [yourmnbbn/smext-fakequeries#25]
sm plugins list
example_fakeplayers.smx (Example - Fake players): Required extension "fakequeries" file("fakequeries.ext") not running

and ext ext list
[07] <FAILED> file "fakequeries.ext.2.csgo.so": /lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/server59748/game/csgo/addons/sourcemod/extensions/fakequeries.ext.2.csgo.so)

help me(?

**Comment by ua-player-ua** [comment]
please compile CXXABI_1.3.7,

**Comment by yourmnbbn** [comment]
Update your libstdc++ or compile the extension yourself could solve this.

**Comment by ua-player-ua** [comment]
> Update your libstdc++ or compile the extension yourself could solve this.

I can not do it. I'm afraid I'll break everything, can I ask you to compile? I will be very grateful to you as well as many here who will face this.

God bless you!
