### ISSUE TITLE
Update csgo 02/02/2023

### ISSUE THREAD

**Issue by shadowgaming24** [yourmnbbn/smext-fakequeries#27]
Anyone have a fix for the update of 02/02/2023?

```
L 02/03/2023 - 20:40:27: [SM] Unable to load extension "fakequeries.ext": Failed to get address of g_pSteamSocketMgr
```

**Comment by yourmnbbn** [comment]
Thanks for the feedback and I‘ll update this within a few hours.

**Comment by yourmnbbn** [comment]
PR #28 has updated all the latest signatures and offsets, and it has been tested. Release has been updated.
