### ISSUE TITLE
Crashes on update

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/smext-fakequeries#7]
Hi! So after [todays update](https://blog.counter-strike.net/index.php/2021/12/36575/) [SteamAPI_SteamGameServer_v013](https://github.com/yourmnbbn/smext-fakequeries/blob/main/extension.cpp#L176) have changed to `SteamAPI_SteamGameServer_v014`. Also, I would recommend adding `return false` to all those 3 functions to avoid possible crashes in the future (like today):
![image](https://user-images.githubusercontent.com/4301144/145659044-00ec5cf6-9ce8-4a17-b1f6-5c34f7e98c46.png)
(Correct me if I'm wrong, as I'm still learning)

**Comment by yourmnbbn** [comment]
Ah, thanks. I'll update soon. Yes you can return false on getting interface pointer failure. I'm planning to get rid of the symbol searching on other interfaces except getting SteamGameServer pointer and use virtual calling instead, maybe along with the challenge fixes.

**Comment by yourmnbbn** [comment]
I've update my challenge fix to brach v1.3.0. It's been tested working on windows. I haven't got time to test it on linux. If you are interested in it you can give it a try. Basic idea is to force the steam api implementation uses the extension's challenge system. So even if not querying extension handled packet, the challenge response will still be generated by the extension.
